language: java

git:
  depth: 1

before_install:
  - wget http://services.gradle.org/distributions/gradle-5.6.2-bin.zip -P /tmp
  - unzip -d /opt/gradle /tmp/gradle-*.zip
  - export GRADLE_HOME=/opt/gradle/gradle-5.6.2
  - export PATH=$GRADLE_HOME/bin:$PATH

install: true

script:
  - gradle cleanTest test
